import React, { useEffect, useState, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { cellService } from "../services/cellService";
import { memberService } from "../services/memberService";
import type {
  CreateCellRequest,
  CellFormErrors,
  MemberDto,
  CellDto,
} from "../types";
import { useAuth } from "../hooks/useAuth";
import SimpleSearchableSelect from "../components/SimpleSearchableSelect";
import { formatDisplayName } from "../utils/memberUtils";

const AddCellPage: React.FC = () => {
  const navigate = useNavigate();
  const { user } = useAuth();

  const [formData, setFormData] = useState<CreateCellRequest>({
    name: "",
    description: "",
  });

  const [members, setMembers] = useState<MemberDto[]>([]);
  const [allCells, setAllCells] = useState<CellDto[]>([]);
  const [formErrors, setFormErrors] = useState<CellFormErrors>({});
  const [loading, setLoading] = useState<boolean>(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [isCellNameAutoGenerated, setIsCellNameAutoGenerated] = useState(false);

  // ✅ 화면용 현재 연도 (셀 생성 기준 연도 안내)
  const currentYear = useMemo(() => new Date().getFullYear(), []);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const membersData = await memberService.getAllMembers({ size: 1000 });
        setMembers(membersData.content);

        const cellsData = await cellService.getAllCells({
          active: true,
          year: new Date().getFullYear(), // 현재 연도 기준으로 기존 셀 조회
          size: 1000,
        });
        setAllCells(cellsData.content);
      } catch (err) {
        console.error("Failed to fetch data for dropdowns:", err);
      }
    };
    fetchData();
  }, []);

  const existingLeaderIds = useMemo(() => {
    const leaderIds = new Set<number>();
    allCells.forEach((cell) => {
      if (cell.leader?.id) {
        leaderIds.add(cell.leader.id);
      }
    });
    return leaderIds;
  }, [allCells]);

  const availableLeaderOptions = useMemo(
    () =>
      members
        .filter(
          (member) =>
            !existingLeaderIds.has(member.id) &&
            member.id !== formData.viceLeaderId
        )
        .map((m) => ({ value: m.id, label: formatDisplayName(m, members) })),
    [members, existingLeaderIds, formData.viceLeaderId]
  );

  const memberOptions = useMemo(
    () =>
      members
        .filter(
          (member) =>
            !existingLeaderIds.has(member.id) && member.id !== formData.leaderId
        )
        .map((m) => ({
          value: m.id,
          label: formatDisplayName(m, members),
        })),
    [members, existingLeaderIds, formData.leaderId]
  );

  // EXECUTIVE만 접근 가능
  if (!user || user.role !== "EXECUTIVE") {
    navigate("/admin/cells");
    return null;
  }

  const handleFormChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
    setFormErrors((prev) => ({ ...prev, [name]: undefined }));

    // 셀 이름이 수동으로 변경되면 자동 생성 상태를 해제
    if (name === "name") {
      setIsCellNameAutoGenerated(false);
    }
  };

  const handleMemberSelect = (
    field: "leaderId" | "viceLeaderId",
    memberId: number | undefined
  ) => {
    setFormData((prev) => {
      const newFormData: CreateCellRequest = { ...prev, [field]: memberId };

      // 셀장 선택 시: 기본 셀 이름 자동 생성
      if (field === "leaderId" && memberId) {
        const leader = members.find((m) => m.id === memberId);
        if (leader) {
          newFormData.name = `${leader.name}셀`;
          setIsCellNameAutoGenerated(true);
        }
      } else if (field === "leaderId" && !memberId) {
        newFormData.name = "";
        setIsCellNameAutoGenerated(false);
      }
      return newFormData;
    });
    setFormErrors((prev) => ({ ...prev, [field]: undefined }));
  };

  const validateForm = (): CellFormErrors => {
    const newErrors: CellFormErrors = {};

    if (!formData.leaderId) {
      newErrors.leaderId = "셀장은 필수입니다.";
    }
    if (!formData.name?.trim()) {
      newErrors.name = "셀 이름은 필수입니다.";
    }

    return newErrors;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    const validationErrors = validateForm();
    if (Object.keys(validationErrors).length > 0) {
      setFormErrors(validationErrors);
      return;
    }

    setLoading(true);
    try {
      const newCell = await cellService.createCell(formData);

      // 셀 생성 성공 후, 셀장의 role을 CELL_LEADER로 업데이트
      if (formData.leaderId) {
        try {
          await memberService.updateMember(formData.leaderId, {
            role: "CELL_LEADER",
            cellId: newCell.id,
          });
        } catch (roleUpdateError) {
          console.error(
            `셀은 생성되었지만, 셀장(${formData.leaderId})의 role 업데이트에 실패했습니다.`,
            roleUpdateError
          );
        }
      }

      navigate("/admin/cells");
    } catch (err: any) {
      console.error("셀 생성 실패:", err);
      setSubmitError(err.response?.data?.message || "셀 생성에 실패했습니다.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container mx-auto px-4 py-8 max-w-2xl">
      <h1 className="text-3xl font-bold text-gray-900 mb-2">새 셀 추가</h1>

      {/* ✅ 올해 기준 연도 안내 */}
      <p className="mb-6 text-sm text-gray-500">
        현재 기준 연도:{" "}
        <span className="font-medium text-gray-800">{currentYear}년</span>
      </p>

      <form onSubmit={handleSubmit} className="space-y-6">
        {submitError && (
          <div className="p-3 text-sm font-medium text-red-700 bg-red-100 border border-red-400 rounded-md">
            {submitError}
          </div>
        )}

        {/* 셀장 선택 */}
        <div>
          <label className="block text-sm font-medium text-gray-700">
            셀장 <span className="text-red-500">*</span>
          </label>
          <SimpleSearchableSelect
            options={availableLeaderOptions}
            value={formData.leaderId}
            onChange={(value) =>
              handleMemberSelect(
                "leaderId",
                typeof value === "number" ? value : undefined
              )
            }
            placeholder="셀장을 선택하세요..."
          />
          {formErrors.leaderId && (
            <p className="mt-1 text-sm text-red-600">{formErrors.leaderId}</p>
          )}
        </div>

        {/* 셀 이름 */}
        <div>
          <label className="block text-sm font-medium text-gray-700">
            셀 이름 <span className="text-red-500">*</span>
          </label>
          <input
            name="name"
            type="text"
            required
            value={formData.name || ""}
            onChange={handleFormChange}
            disabled={isCellNameAutoGenerated}
            className="block w-full px-3 py-2 mt-1 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
          />
          {formErrors.name && (
            <p className="mt-1 text-sm text-red-600">{formErrors.name}</p>
          )}
        </div>

        {/* 예비셀장 */}
        <div>
          <label className="block text-sm font-medium text-gray-700">
            예비셀장
          </label>
          <SimpleSearchableSelect
            options={memberOptions}
            value={formData.viceLeaderId}
            onChange={(value) =>
              handleMemberSelect(
                "viceLeaderId",
                typeof value === "number" ? value : undefined
              )
            }
            placeholder="예비셀장을 선택하세요..."
          />
          {formErrors.viceLeaderId && (
            <p className="mt-1 text-sm text-red-600">
              {formErrors.viceLeaderId}
            </p>
          )}
        </div>

        {/* 설명 */}
        <div>
          <label className="block text-sm font-medium text-gray-700">
            설명
          </label>
          <textarea
            name="description"
            rows={3}
            value={formData.description || ""}
            onChange={handleFormChange}
            className="block w-full px-3 py-2 mt-1 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
          />
        </div>

        <div className="flex justify-end pt-4">
          <button
            type="button"
            onClick={() => navigate("/admin/cells")}
            className="bg-gray-300 text-gray-800 px-4 py-2 rounded-md mr-2"
            disabled={loading}
          >
            취소
          </button>
          <button
            type="submit"
            className="bg-indigo-600 text-white px-4 py-2 rounded-md"
            disabled={loading}
          >
            {loading ? "생성 중..." : "생성"}
          </button>
        </div>
      </form>
    </div>
  );
};

export default AddCellPage;
