import React, { useEffect, useState, useMemo } from "react";
import { useNavigate } from "react-router-dom";
import { cellService } from "../services/cellService";
import { memberService } from "../services/memberService";
import type {
  CreateCellRequest,
  CellFormErrors,
  MemberDto,
  CellDto,
} from "../types";
import { useAuth } from "../hooks/useAuth";
import SimpleSearchableSelect from "../components/SimpleSearchableSelect";
import { formatNameWithBirthdate } from "../utils/memberUtils";

const AddCellPage: React.FC = () => {
  const navigate = useNavigate();
  const { user } = useAuth();

  const [formData, setFormData] = useState<CreateCellRequest>({
    name: "",
    description: "",
  });

  const [members, setMembers] = useState<MemberDto[]>([]);
  const [allCells, setAllCells] = useState<CellDto[]>([]);
  const [formErrors, setFormErrors] = useState<CellFormErrors>({});
  const [loading, setLoading] = useState<boolean>(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [isCellNameAutoGenerated, setIsCellNameAutoGenerated] = useState(false);

  // 새 셀에 함께 배정할 멤버 (다중 선택)
  const [selectedMemberIds, setSelectedMemberIds] = useState<number[]>([]);
  const [membersSearchTerm, setMembersSearchTerm] = useState("");
  const [isMembersDropdownOpen, setIsMembersDropdownOpen] = useState(false); // ★ 셀 구성원 드롭다운 열림 상태

  // 화면용 현재 연도
  const currentYear = useMemo(() => new Date().getFullYear(), []);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const membersData = await memberService.getAllMembers({ size: 1000 });
        setMembers(membersData.content);

        const cellsData = await cellService.getAllCells({
          active: true,
          year: new Date().getFullYear(), // 현재 연도 기준으로 기존 셀 조회
          size: 1000,
        });
        setAllCells(cellsData.content);
      } catch (err) {
        console.error("Failed to fetch data for dropdowns:", err);
      }
    };
    fetchData();
  }, []);

  const existingLeaderIds = useMemo(() => {
    const leaderIds = new Set<number>();
    allCells.forEach((cell) => {
      if (cell.leader?.id) {
        leaderIds.add(cell.leader.id);
      }
    });
    return leaderIds;
  }, [allCells]);

  // 셀장 후보: 셀에 속해 있지 않고, 리더가 아니고, 현재 선택된 예비셀장 아님
  const availableLeaderOptions = useMemo(
    () =>
      members
        .filter(
          (member) =>
            !member.cell && // 이미 셀에 속한 사람 제외
            !existingLeaderIds.has(member.id) &&
            member.id !== formData.viceLeaderId
        )
        .map((m) => ({
          value: m.id,
          // 생년월일 포함 표시
          label: formatNameWithBirthdate(m),
        })),
    [members, existingLeaderIds, formData.viceLeaderId]
  );

  // 예비셀장 후보: 셀에 속해 있지 않고, 리더가 아니고, 현재 선택된 셀장 아님
  const viceLeaderOptions = useMemo(
    () =>
      members
        .filter(
          (member) =>
            !member.cell && // 이미 셀에 속한 사람 제외
            !existingLeaderIds.has(member.id) &&
            member.id !== formData.leaderId
        )
        .map((m) => ({
          value: m.id,
          // 생년월일 포함 표시
          label: formatNameWithBirthdate(m),
        })),
    [members, existingLeaderIds, formData.leaderId]
  );

  // EXECUTIVE만 접근 가능
  useEffect(() => {
    if (user && user.role !== "EXECUTIVE") {
      navigate("/admin/cells");
    }
  }, [user, navigate]);

  if (!user || user.role !== "EXECUTIVE") {
    return null;
  }

  const handleFormChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
    setFormErrors((prev) => ({ ...prev, [name]: undefined }));

    // 셀 이름이 수동으로 변경되면 자동 생성 상태를 해제
    if (name === "name") {
      setIsCellNameAutoGenerated(false);
    }
  };

  const handleMemberSelect = (
    field: "leaderId" | "viceLeaderId",
    memberId: number | undefined
  ) => {
    setFormData((prev) => {
      const newFormData: CreateCellRequest = { ...prev, [field]: memberId };

      // 셀장 선택 시: 기본 셀 이름 자동 생성
      if (field === "leaderId" && memberId) {
        const leader = members.find((m) => m.id === memberId);
        if (leader) {
          newFormData.name = `${leader.name}셀`;
          setIsCellNameAutoGenerated(true);
        }
      } else if (field === "leaderId" && !memberId) {
        newFormData.name = "";
        setIsCellNameAutoGenerated(false);
      }
      return newFormData;
    });
    setFormErrors((prev) => ({ ...prev, [field]: undefined }));

    // 셀장/예비셀장으로 선택된 인원은 셀 구성원에서 제거
    if (memberId) {
      setSelectedMemberIds((prev) => prev.filter((id) => id !== memberId));
    }
  };

  const validateForm = (): CellFormErrors => {
    const newErrors: CellFormErrors = {};

    if (!formData.leaderId) {
      newErrors.leaderId = "셀장은 필수입니다.";
    }
    if (!formData.name?.trim()) {
      newErrors.name = "셀 이름은 필수입니다.";
    }

    return newErrors;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitError(null);

    const validationErrors = validateForm();
    if (Object.keys(validationErrors).length > 0) {
      setFormErrors(validationErrors);
      return;
    }

    setLoading(true);
    try {
      // CreateCellRequest 페이로드에 memberIds를 포함
      const payload: CreateCellRequest = {
        ...formData,
        memberIds: selectedMemberIds,
      };

      await cellService.createCell(payload);

      // 셀 생성 성공 후, 셀장의 role을 CELL_LEADER로 업데이트
      // (백엔드가 자동으로 처리하지 않을 경우를 대비)
      if (formData.leaderId) {
        try {
          await memberService.updateMember(formData.leaderId, {
            role: "CELL_LEADER",
          });
        } catch (roleUpdateError) {
          console.error(
            `셀은 생성되었지만, 셀장(${formData.leaderId})의 role 업데이트에 실패했습니다. 수동으로 변경해주세요.`,
            roleUpdateError
          );
        }
      }

      navigate("/admin/cells");
    } catch (err: any) {
      console.error("셀 생성 실패:", err);
      setSubmitError(err.response?.data?.message || "셀 생성에 실패했습니다.");
    } finally {
      setLoading(false);
    }
  };

  // 셀 구성원 후보: 아직 셀에 속하지 않고, 셀장/예비셀장이 아닌 사람
  const candidateMembers = useMemo(
    () =>
      members.filter((member) => {
        if (member.cell) return false;
        if (formData.leaderId && member.id === formData.leaderId) return false;
        if (formData.viceLeaderId && member.id === formData.viceLeaderId)
          return false;
        return true;
      }),
    [members, formData.leaderId, formData.viceLeaderId]
  );

  // 검색 + 후보 필터
  const filteredMembers = useMemo(
    () =>
      candidateMembers.filter((member) =>
        formatNameWithBirthdate(member)
          .toLowerCase()
          .includes(membersSearchTerm.toLowerCase())
      ),
    [candidateMembers, membersSearchTerm]
  );

  // 선택된 셀 구성원 상세 정보 (표시용)
  const selectedMembers = useMemo(
    () => members.filter((m) => selectedMemberIds.includes(m.id)),
    [members, selectedMemberIds]
  );

  const handleToggleCellMember = (memberId: number) => {
    setSelectedMemberIds((prev) => {
      if (prev.includes(memberId)) {
        return prev.filter((id) => id !== memberId);
      }
      return [...prev, memberId];
    });
  };

  const handleRemoveCellMember = (memberId: number) => {
    setSelectedMemberIds((prev) => prev.filter((id) => id !== memberId));
  };

  return (
    <div className="max-w-2xl mx-auto px-4 sm:px-6 py-5 sm:py-8">
      {/* 헤더 영역 */}
      <div className="mb-4 sm:mb-6">
        <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-1">
          새 셀 추가
        </h1>
        <p className="text-xs sm:text-sm text-gray-500">
          현재 기준 연도:{" "}
          <span className="font-medium text-gray-800">{currentYear}년</span>
        </p>
      </div>

      {/* 카드형 폼 영역 */}
      <form
        onSubmit={handleSubmit}
        className="space-y-5 sm:space-y-6 bg-white rounded-2xl shadow-sm border border-gray-100 p-4 sm:p-6"
      >
        {submitError && (
          <div className="p-3 text-xs sm:text-sm font-medium text-red-700 bg-red-50 border border-red-200 rounded-md">
            {submitError}
          </div>
        )}

        {/* 셀장 선택 */}
        <div>
          <label className="block text-sm font-medium text-gray-700">
            셀장 <span className="text-red-500">*</span>
          </label>
          <div className="mt-1">
            <SimpleSearchableSelect
              options={availableLeaderOptions}
              value={formData.leaderId}
              onChange={(value) =>
                handleMemberSelect(
                  "leaderId",
                  typeof value === "number" ? value : undefined
                )
              }
              placeholder="셀장을 선택하세요..."
            />
          </div>
          {formErrors.leaderId && (
            <p className="mt-1 text-xs sm:text-sm text-red-600">
              {formErrors.leaderId}
            </p>
          )}
        </div>

        {/* 셀 이름 */}
        <div>
          <label className="block text-sm font-medium text-gray-700">
            셀 이름 <span className="text-red-500">*</span>
          </label>
          <input
            name="name"
            type="text"
            required
            value={formData.name || ""}
            onChange={handleFormChange}
            disabled={isCellNameAutoGenerated}
            className={`mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm text-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 ${
              isCellNameAutoGenerated ? "bg-gray-50 text-gray-700" : ""
            }`}
          />
          {isCellNameAutoGenerated && (
            <p className="mt-1 text-xs text-gray-500">
              셀장을 선택하면 자동으로 &quot;이름셀&quot; 형식으로 셀 이름이
              설정됩니다. 필요하다면 셀장을 해제한 뒤 직접 입력할 수 있습니다.
            </p>
          )}
          {formErrors.name && (
            <p className="mt-1 text-xs sm:text-sm text-red-600">
              {formErrors.name}
            </p>
          )}
        </div>

        {/* 예비셀장 */}
        <div>
          <label className="block text-sm font-medium text-gray-700">
            예비셀장
          </label>
          <div className="mt-1">
            <SimpleSearchableSelect
              options={viceLeaderOptions}
              value={formData.viceLeaderId}
              onChange={(value) =>
                handleMemberSelect(
                  "viceLeaderId",
                  typeof value === "number" ? value : undefined
                )
              }
              placeholder="예비셀장을 선택하세요..."
            />
          </div>
          {formErrors.viceLeaderId && (
            <p className="mt-1 text-xs sm:text-sm text-red-600">
              {formErrors.viceLeaderId}
            </p>
          )}
        </div>

        {/* 셀 구성원 (셀장/예비셀장과 비슷한 셀렉트 스타일 + 드롭다운 멀티선택) */}
        <div>
          <label className="block text-sm font-medium text-gray-700">
            셀 구성원
          </label>
          <p className="mt-1 mb-2 text-xs text-gray-500">
            아직 어떤 셀에도 속하지 않은 멤버만 선택할 수 있습니다.<br></br>
            셀장/예비셀장으로 선택된 인원은 자동으로 후보에서 제외됩니다.
          </p>

          {/* ✅ 셀장/예비셀장과 비슷한 “한 줄짜리 셀렉트” */}
          <div className="mt-1 relative">
            <button
              type="button"
              onClick={() => setIsMembersDropdownOpen((prev) => !prev)}
              className="w-full flex items-center justify-between px-3 py-2 border border-gray-300 rounded-md shadow-sm text-sm bg-white focus:outline-none focus:ring-1 focus:ring-indigo-500 focus:border-indigo-500"
            >
              {selectedMembers.length === 0 ? (
                <span className="text-gray-400">셀 구성원을 선택하세요...</span>
              ) : (
                <span className="text-gray-800 truncate">
                  {selectedMembers
                    .map((m) => formatNameWithBirthdate(m))
                    .join(", ")}
                </span>
              )}
              <span className="ml-2 text-gray-400 text-xs">
                {isMembersDropdownOpen ? "▲" : "▼"}
              </span>
            </button>

            {/* ▼ 드롭다운 패널 (검색 + 체크박스 리스트) */}
            {isMembersDropdownOpen && (
              <div className="absolute z-20 mt-1 w-full bg-white border border-gray-200 rounded-md shadow-lg">
                {/* 검색창 */}
                <div className="p-2 border-b border-gray-200">
                  <input
                    type="text"
                    placeholder="표시된 목록에서 이름으로 검색..."
                    value={membersSearchTerm}
                    onChange={(e) => setMembersSearchTerm(e.target.value)}
                    className="w-full px-2 py-1.5 border border-gray-300 rounded-md text-xs sm:text-sm focus:outline-none focus:ring-1 focus:ring-indigo-500"
                  />
                </div>

                {/* 리스트 영역 */}
                <div className="max-h-60 overflow-y-auto">
                  {filteredMembers.length === 0 ? (
                    <p className="p-3 text-xs sm:text-sm text-gray-500">
                      {candidateMembers.length === 0
                        ? "추가할 수 있는 멤버가 없습니다."
                        : "검색 결과가 없습니다."}
                    </p>
                  ) : (
                    <ul>
                      {filteredMembers.map((member) => (
                        <li
                          key={member.id}
                          className={`flex items-center text-xs sm:text-sm hover:bg-indigo-50 ${
                            selectedMemberIds.includes(member.id)
                              ? "bg-indigo-100"
                              : ""
                          }`}
                        >
                          <label
                            htmlFor={`cell-member-checkbox-${member.id}`}
                            className="flex items-center w-full px-3 py-2 cursor-pointer"
                          >
                            <input
                              id={`cell-member-checkbox-${member.id}`}
                              type="checkbox"
                              checked={selectedMemberIds.includes(member.id)}
                              onChange={() => handleToggleCellMember(member.id)}
                              className="mr-2 h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"
                            />
                            {formatNameWithBirthdate(member)}
                          </label>
                        </li>
                      ))}
                    </ul>
                  )}
                </div>

                {/* 하단 요약 + 닫기 버튼 (옵션) */}
                <div className="flex items-center justify-between px-3 py-2 border-t border-gray-100 bg-gray-50">
                  <span className="text-xs text-gray-600">
                    선택된 구성원:{" "}
                    <span className="font-semibold">
                      {selectedMemberIds.length}명
                    </span>
                  </span>
                  <button
                    type="button"
                    onClick={() => setIsMembersDropdownOpen(false)}
                    className="text-xs text-indigo-600 hover:text-indigo-800 font-medium"
                  >
                    닫기
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* 선택된 셀원 배지 표시 */}
          {selectedMembers.length > 0 && (
            <div className="mt-2 flex flex-wrap gap-2">
              {selectedMembers.map((m) => (
                <span
                  key={m.id}
                  className="inline-flex items-center px-2.5 py-1 rounded-full text-xs bg-indigo-50 text-indigo-700 border border-indigo-100"
                >
                  {formatNameWithBirthdate(m)}
                  <button
                    type="button"
                    onClick={() => handleRemoveCellMember(m.id)}
                    className="ml-1 text-indigo-400 hover:text-indigo-700"
                  >
                    ✕
                  </button>
                </span>
              ))}
            </div>
          )}

          <p className="mt-1 text-xs text-gray-600">
            현재 선택된 구성원:{" "}
            <span className="font-semibold">{selectedMemberIds.length}명</span>
          </p>
        </div>

        {/* 설명 */}
        <div>
          <label className="block text-sm font-medium text-gray-700">
            설명
          </label>
          <textarea
            name="description"
            rows={3}
            value={formData.description || ""}
            onChange={handleFormChange}
            className="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm text-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 resize-y min-h-[100px] max-h-[240px]"
          />
        </div>

        {/* 버튼 영역 */}
        <div className="pt-2 sm:pt-4 flex flex-col-reverse sm:flex-row sm:justify-end gap-2">
          <button
            type="button"
            onClick={() => navigate("/admin/cells")}
            className="w-full sm:w-auto inline-flex justify-center items-center bg-gray-200 text-gray-800 px-4 py-2 rounded-md text-sm font-medium hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-400 disabled:opacity-60 disabled:cursor-not-allowed"
            disabled={loading}
          >
            취소
          </button>
          <button
            type="submit"
            className="w-full sm:w-auto inline-flex justify-center items-center bg-indigo-600 text-white px-4 py-2 rounded-md text-sm font-semibold hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-60 disabled:cursor-not-allowed"
            disabled={loading}
          >
            {loading ? "생성 중..." : "생성"}
          </button>
        </div>
      </form>
    </div>
  );
};

export default AddCellPage;
